# Schema for the configuration files of the Microsoft Clarity module.
ms_clarity.settings:
  type: config_object
  label: 'Microsoft Clarity settings'
  mapping:
    account:
      type: string
      label: 'Clarity ID'
    visibility:
      type: mapping
      label: 'Visibility'
      mapping:
        request_path_mode:
          type: integer
          label: 'Add tracking to specific pages'
        request_path_pages:
          type: string
          label: 'Pages by their paths'
        user_role_mode:
          type: integer
          label: 'Add tracking for specific roles'
        user_role_roles:
          type: sequence
          label: 'Roles'
          sequence:
            type: string
            label: 'Role'
